management week and goals for week 3
nfarnan/cs1666_organization pull request #12
Opened 2021-06-11 15:42 UTC by keyonzi

2021-06-11 15:48 UTC, nfarnan requested changes
Some of the changes that I'm requesting will require undoing old commits. You're going to have to checkout a previous commit and start a new history from there. Avoiding this difficulty is one reason to work with branches for any new changes. As an easy short cut, you may just want to re-clone the repo to start fresh, and work on branches from there.

Also, you should not submit goals for management weeks that are not your own, and while I will accept you filling out the entire management week schedule, the expectation was that each student would submit a PR for their own week (i.e., if you don't want to look up everyone's Pitt IDs, tell them all to do it themselves and send me individual PRs)

2021-06-11 15:48 UTC, nfarnan commented on management/Roguelike.md
>  	* Manager: NAME
Who is the manger for week 3? They need to be the one to issue the PR with their goals.

2021-06-11 15:48 UTC, nfarnan commented on management/Roguelike.md
> +	* Manager: Trae Yelovich
Please add Pitt IDs (e.g., nlf4) to each manager for easy lookup on my end (should be in the team roster description).

2021-06-11 15:50 UTC, keyonzi commented
Hi Professor,

You recommended for our canonical repo to also do forks and not branches. Which is what I told them. They went ahead with the organization, but as I understood from you, we should fork and not branch. So just a bit confused on that. 

Keyon

> On Jun 11, 2021, at 11:48 AM, Nicholas Farnan ***@***.***> wrote:
> 
> ﻿
> @nfarnan requested changes on this pull request.
> 
> Some of the changes that I'm requesting will require undoing old commits. You're going to have to checkout a previous commit and start a new history from there. Avoiding this difficulty is one reason to work with branches for any new changes. As an easy short cut, you may just want to re-clone the repo to start fresh, and work on branches from there.
> 
> Also, you should not submit goals for management weeks that are not your own, and while I will accept you filling out the entire management week schedule, the expectation was that each student would submit a PR for their own week (i.e., if you don't want to look up everyone's Pitt IDs, tell them all to do it themselves and send me individual PRs)
> 
> In management/Roguelike.md:
> 
> > @@ -11,35 +11,37 @@
>  3. 06/16 - 06/22
>  	* Manager: NAME
> Who is the manger for week 3? They need to be the one to issue the PR with their goals.
> 
> In management/Roguelike.md:
> 
> >  		...
>  4. 06/23 - 06/29
>  	* Manager: NAME
>  	* Goals:
>  		1. GOAL1
>  		...
>  5. 06/30 - 07/6
> -	* Manager: NAME
> +	* Manager: Trae Yelovich
> Please add Pitt IDs (e.g., nlf4) to each manager for easy lookup on my end (should be in the team roster description).
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-06-11 15:57 UTC, nfarnan commented
These techniques are not mutually exclusive, you can have both a fork and branches. I would discourage teams from using only branches on the canonical repository for organization, but I would still encourage you to create branches on your for as you develop new features. This chapter from the git book should give a good description of how you can use branches effectively even as the sole developer of a project:

https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

2021-06-11 16:02 UTC, keyonzi commented
Appreciate it. 

Btw, I withdrew from the other class. Hope it was the smart decision. 

Thanks,
Keyon

> On Jun 11, 2021, at 11:57 AM, Nicholas Farnan ***@***.***> wrote:
> 
> These techniques are not mutually exclusive, you can have both a fork and branches. I would discourage teams from using only branches on the canonical repository for organization, but I would still encourage you to create branches on your for as you develop new features. This chapter from the git book should give a good description of how you can use branches effectively even as the sole developer of a project:

2021-06-16 17:05 UTC, nfarnan commented
OK, we still have a few issues here.

1. This is the organization repo, it does not need the .gitignore
2. You still have changes to the lines for other management weeks (e.g, from "NAME" to ""). I realize this sounds overly particular, but this means that any other pull requests on these lines would need to either a) rebase off of your changes before issuing the PR or b) I have to resolve a merge conflict on those lines. I realize this unnecessarily difficult to just sign up for management weeks, but I would rather have you guys make errors like this in the organization repo than to have them come up a couple of weeks later in your game repo. You can try either resetting your working branch and retrying, or just delete and re-clone the org repo to issue another pull request. This one has gotten a bit convoluted, so I'm closing it.

2021-06-16 17:05 UTC, closed without merging

2021-06-16 20:35 UTC, keyonzi commented
the gitignore was an accident. I was trying to add it to our roguerepo and
accidently added to the wrong place. I thought I had removed it.

I will try and fix the 'NAME' issue

On Wed, Jun 16, 2021 at 1:05 PM Nicholas Farnan ***@***.***>
wrote:

> OK, we still have a few issues here.
>
>    1. This is the organization repo, it does not need the .gitignore
>    2. You still have changes to the lines for other management weeks
>    (e.g, from "NAME" to ""). I realize this sounds overly particular, but this
>    means that any other pull requests on these lines would need to either a)
>    rebase off of your changes before issuing the PR or b) I have to resolve a
>    merge conflict on those lines. I realize this unnecessarily difficult to
>    just sign up for management weeks, but I would rather have you guys make
>    errors like this in the organization repo than to have them come up a
>    couple of weeks later in your game repo. You can try either resetting your
>    working branch and retrying, or just delete and re-clone the org repo to
>    issue another pull request. This one has gotten a bit convoluted, so I'm
>    closing it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nfarnan/cs1666_organization/pull/12#issuecomment-862554713>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADF44K4FLTKPPT32OPRJEUTTTDKVJANCNFSM46Q7WTJA>
> .
>