Goals
nfarnan/cs1666_organization pull request #17
Opened 2020-09-18 16:06 UTC by Ruzakiff

make main menu
make basic game loop and player movement 
make player image

2020-09-18 16:22 UTC, nfarnan requested changes

2020-09-18 16:22 UTC, nfarnan commented on management/SpeedRun.md
> +		1. Make Basic game loop, player movement
Specifically, what movement will you implement this week?

2020-09-18 16:22 UTC, nfarnan commented on management/SpeedRun.md
> +		1. Make Player Image
And display it to the screen

2020-09-18 16:41 UTC, Ruzakiff commented on management/SpeedRun.md
> +		1. Make Basic game loop, player movement
forward, left/right

2020-09-18 16:41 UTC, Ruzakiff commented on management/SpeedRun.md
> +		1. Make Player Image
yes

2020-09-23 18:44 UTC, cas380 commented
This week's goals got added to this pull request as commits, I can't open a new one.

1. Add blocks the player can collide with and fine-tune movement
2. Randomly generate some kind of path/obstacles out of the collide-able blocks (or placeholder blocks)
3. Create initial networking code, ping client to client with up to 4 players

2020-09-23 18:50 UTC, cas380 approved these changes

2020-09-23 21:32 UTC, nfarnan commented
I see. We've got a couple of issues with this pull request. First, my requested edits for last week's goals were never made. Apparently I should have closed that pull request. Also, this PR includes changes to files throughout the repository. I'm not sure what you did to edit all of the files, but you'll need to rebase your repository on the current state of the organization repo and try again. Be sure that you are only changing the management file for your team.

For now, I'm closing this PR.

2020-09-23 21:32 UTC, closed without merging