Added 9/2 - 9/8 Management Information For Metroidvania
nfarnan/cs1666_organization pull request #2
Opened 2020-08-31 21:11 UTC by ElmaK141

Added that I, Kristofer Leo Elmarsson, will be the manager for Metroidvania the first week, 9/2 - 9/8, and that the goal is simply "Establish Teams" as instructed.

2020-09-02 00:26 UTC, nfarnan commented on teams/Metroidvania.md
> +	* Julian P.
Need a full name for all students

2020-09-05 13:28 UTC, nfarnan requested changes

2020-09-05 13:28 UTC, nfarnan commented on teams/Metroidvania.md
> +https://github.com/ElmaK141/Metroidvania_CS1666
I can't view this repo, please add me.

2020-09-05 13:28 UTC, nfarnan commented on teams/Metroidvania.md
> +	* Simulate Gravity
Gravity, itself is a bit too simple to be a milestone here.

2020-09-05 13:28 UTC, nfarnan commented on teams/Metroidvania.md
> +	* Implement Advanced Movement Gadgets
Both of these are a bit too simple as well.

2020-09-05 13:28 UTC, nfarnan commented on teams/Metroidvania.md
> +	* Rigid Body Collision
With more details of what will be colliding, this should be enough on its own.

2020-09-05 13:28 UTC, nfarnan commented on teams/Metroidvania.md
> +	* Implement basic enemy AI
Need more details of the behaviors that you'll be attempting and why it will be challenging enough to be an advanced topic milestone.

2020-09-05 13:28 UTC, nfarnan commented on teams/Metroidvania.md
> +	* Have AI react to the geometry of the levels
How will you coordinate with the procedural level gen team? What aspects of the levels are you striving to work around?

2020-09-05 13:28 UTC, nfarnan commented on teams/Metroidvania.md
> +	* Implemnt boss AI
How  do you plan for the boss AI to differ from typical enemies?

2020-09-05 13:28 UTC, nfarnan commented on teams/Metroidvania.md
> +	* Create a system that generates levels according to the equipment/powerups the player has
This is going to be especially tough, managing the backtracking/gating of certain areas until specific powerups have been applied. At the moment, I'm not sold on this as an advanced topic. Not saying we can't get there, but I'll need more details.

2020-09-05 13:28 UTC, nfarnan commented on teams/Metroidvania.md
> +* Implement weaponry
How many weapons? Melee or ranged? How will they differ?

2020-09-05 13:28 UTC, nfarnan commented on teams/Metroidvania.md
> +* Implement enemy AI
How many enemy types? What behaviors are you striving for?

2020-09-05 13:28 UTC, nfarnan commented on teams/Metroidvania.md
> +* Design the world
Goes for the past two milestones: how big? what is your scale?

2020-09-05 13:28 UTC, nfarnan commented on teams/Metroidvania.md
> +* Implement quest system
Need a few more details here as well. What types of quests will you send the player on? How many quests will you implement this term?

2020-09-08 01:13 UTC, ElmaK141 commented on teams/Metroidvania.md
> +https://github.com/ElmaK141/Metroidvania_CS1666
Added

2020-09-08 20:03 UTC, nfarnan approved these changes

2020-09-08 20:03 UTC, merged