Tactical RPG Team Description - Management Week 0
nfarnan/cs1666_organization pull request #2
Opened 2021-09-20 13:31 UTC by KalebRaymond

Added markup file with the team description for the tactical rpg team.

2021-09-21 13:18 UTC, nfarnan requested changes
Overall looks pretty good. Would like a few clarifications on AI and networking goals, though.

2021-09-21 13:18 UTC, nfarnan commented on teams/Tactical_RPG_team_description.md
> +* Multiplayer room creation and joining
Will the server be a separate process? Or do you plan on P2P networking?

2021-09-21 13:18 UTC, nfarnan commented on teams/Tactical_RPG_team_description.md
> +    	* Enemy should choose whether to prioritize attacking barbarians that are out of the way versus going directly for the player.
Need some insights or ideas on how the enemy AI will make these descisions (e.g., what algorithms or internal representations to use)

2021-09-22 13:35 UTC, KalebRaymond commented
AI and Networking subtopics updated

2021-09-22 15:09 UTC, nfarnan requested changes
One more minor change (my fault, I missed it the first time), cur the multi threading. Would probably be unnecessary, and would be a tall order to implement if all of your team isn't familiar with the challenges of threaded applications.

2021-09-22 15:09 UTC, nfarnan commented on teams/Tactical_RPG_team_description.md
> +	* We may have to implement multithreading/parallel programming in order to achieve an acceptable runtime
Cut the multithreading, you should be fine on runtime (the requirements of the game are, other than this, very low). If anyone hasn't take CS1550, this would be an especially tall order

2021-09-22 15:26 UTC, KalebRaymond commented
Removed multithreading comment from the AI Subtopic section

2021-09-22 15:32 UTC, nfarnan approved these changes
Looks good!

2021-09-22 15:32 UTC, merged