Outline for AI Presentation 1
nfarnan/cs1666_organization pull request #25
Opened 2020-09-29 02:23 UTC by eh0w

2020-09-29 15:00 UTC, nfarnan requested changes

2020-09-29 15:00 UTC, nfarnan commented on adv_topics/ai.md
> +* How does AI Work?
Change to "Some examples of AI", you're not presenting an exhaustive look at approaches to AI (nor would I expect you  to/would it be possible to in the time constraints).

2020-09-29 22:55 UTC, eh0w commented on adv_topics/ai.md
> +* How does AI Work?
So should we remove "How does AI Work" all together, and just focus on the examples there?

2020-09-30 16:36 UTC, nfarnan commented on adv_topics/ai.md
> +* How does AI Work?
My suggestion was only to change the title. I think a brief overview of these topics will be fine.

2020-09-30 19:18 UTC, merged