Teams, Managers, and General Milestones
nfarnan/cs1666_organization pull request #4
Opened 2020-09-04 18:02 UTC by Markoozy

Organized Team into advanced topic subteams, organized managers, wrote game description, started on General Milestones.

2020-09-04 21:04 UTC, nfarnan commented on management/PuzzleStealth.md
> -1. 9/9 - 9/15
Markdown generally doesn't care what the numbers are, e.g., leaving them all 1. will still render as 1., then 2., etc.
No need to change, just FYI
https://guides.github.com/features/mastering-markdown/

2020-09-04 21:14 UTC, nfarnan requested changes

2020-09-04 21:14 UTC, nfarnan commented on teams/PuzzleStealth.md
> +https://github.com/1666-Puzzle-Stealth/StealthPuzzle
I can't view this repo, please add me as a member so that I can access it.

2020-09-04 21:14 UTC, nfarnan commented on teams/PuzzleStealth.md
> +
The advanced topic teams need to be as closely balanced as possible. One student will need to move from AI to Level Gen.

2020-09-04 21:14 UTC, nfarnan commented on teams/PuzzleStealth.md
> +* Agent can move around in an environment
Size of environment? General scale? It's fine to move this question to the level gen milestone.

2020-09-04 21:14 UTC, nfarnan commented on teams/PuzzleStealth.md
> +* Hacker can access subsystems
How many is the goal? Examples?

2020-09-04 21:14 UTC, nfarnan commented on teams/PuzzleStealth.md
> +* Both players have puzzles to solve to access systems
Balancing the creation of puzzles with random level gen will be tricky. Any examples of the type of puzzles?

2020-09-04 21:14 UTC, nfarnan commented on teams/PuzzleStealth.md
> +
What enemy types will exist? Just guards, all the same type? What is their expected behavior (will tie in with AI milestones)?

2020-09-04 21:14 UTC, nfarnan commented on management/PuzzleStealth.md
> +	* Manager: Marko Djurdjevic
I needed your sign-up by Wednesday, so this part is late.

2020-09-04 22:21 UTC, Markoozy commented on teams/PuzzleStealth.md
> +https://github.com/1666-Puzzle-Stealth/StealthPuzzle
I have invited you to the Puzzle Stealth Organization

2020-09-04 22:23 UTC, Markoozy commented on management/PuzzleStealth.md
> +	* Manager: Marko Djurdjevic
I didn't realize. I just thought we needed to tell you which of us was the manager, which I did during class. My bad.

2020-09-05 17:07 UTC, Markoozy commented on teams/PuzzleStealth.md
> +
Erik Houseworth has been moved to Level Generation

2020-09-05 17:58 UTC, Markoozy commented on teams/PuzzleStealth.md
> +* Hacker can access subsystems
Fixed

2020-09-05 17:58 UTC, Markoozy commented on teams/PuzzleStealth.md
> +* Both players have puzzles to solve to access systems
Gave examples.

2020-09-05 17:58 UTC, Markoozy commented on teams/PuzzleStealth.md
> +
Specified enemy types/states.

2020-09-05 17:59 UTC, Markoozy commented on teams/PuzzleStealth.md
> +* Agent can move around in an environment
Specified. Grid based system for level creation.

2020-09-07 14:43 UTC, nfarnan approved these changes

2020-09-07 14:43 UTC, merged