Fighting Team Proposal
nfarnan/cs1666_organization pull request #4
Opened 2021-06-07 16:17 UTC by cps41

2021-06-07 16:35 UTC, cps41 commented
Usernames and full names to be filled in, just wanted feedback on everything else asap.

2021-06-07 17:26 UTC, nfarnan requested changes
Overall I need some more specifics so that I can effectively grade the project at the end of the term.

2021-06-07 17:26 UTC, nfarnan commented on teams/Fighting.md
> +https://github.com/kem243/Fighting-Game
You need to grant my user (nfarnan) access to this repository.

2021-06-07 17:26 UTC, nfarnan commented on teams/Fighting.md
> +Multi-networked Street Fighter platform fighter using physics engine to fight with our favorite programming languages. A throwback that lets us literally fight it out with our top programming languag
Change the start to "Networked multiplayer platform fighter", you mention the Street Fighter influence below, no need to repeat.

2021-06-07 17:26 UTC, nfarnan commented on teams/Fighting.md
> +Physics engine will simulate movement and collisions in a rigid-body format. Basic principles of kinematics will be applied for interactions to allow movement on an XY plane. This includes concepts s
Need some details on what collisions you will simulate (e.g., destructible environments, rolling hazards, player collisions, etc.)

2021-06-07 17:26 UTC, nfarnan commented on teams/Fighting.md
> +* Characters will not collide
Unclear what you mean here. Characters can overlap (so no collision detection at all?), or characters cannot overlap, but will not implement collision physics (e.g., collision detection by no kinematics applied?)

2021-06-07 17:26 UTC, nfarnan commented on teams/Fighting.md
> +* Network multiplayer started
Need a specific goal (e.g, clients can communicate with one another, clients can send hello messages to the server, something like that).

2021-06-07 17:26 UTC, nfarnan commented on teams/Fighting.md
> +* Physics engine started
Similarly, we need a specific goal here

2021-06-07 17:26 UTC, nfarnan commented on teams/Fighting.md
> +* 15%: Networking
What do you want the networking layer to be able to do? Need specific goals for me to be able to grade on.

2021-06-07 17:26 UTC, nfarnan commented on teams/Fighting.md
> +* 15%: Physics Engine
What do you want the physics engine to be able to do? Need specific goals for me to be able to grade on.

2021-06-07 17:26 UTC, nfarnan commented on teams/Fighting.md
> +* 10%: Keyboard Input Working
Need specific goals.

2021-06-07 17:26 UTC, nfarnan commented on teams/Fighting.md
> +* 10%: Health Logic Functional
Need specific goals.

2021-06-07 17:26 UTC, nfarnan commented on teams/Fighting.md
> +* Welcome Screen and Menus
This is a little bit too basic of a stretch goal. You will need something like this for the game to reasonably run. How about implementing a "special" move that is a combination of some directional movement and button presses?

2021-06-07 20:24 UTC, nfarnan commented on teams/Fighting.md
> +https://github.com/kem243/Fighting-Game
I don't need push access, but this is fine.

2021-06-08 18:13 UTC, nfarnan requested changes
Minor update, need an additional requirement for the physics engine.

2021-06-08 18:13 UTC, nfarnan commented on teams/Fighting.md
> +location accordingly, manages forces such as gravity, character weight, and impact due to combat
I'll want a little more for the physics engine. Add a requirement of accounting for falling hazards (e.g., rocks or barrels) that can collide with the stage and player using rigid body physics simulation.

2021-06-08 18:18 UTC, cps41 commented on teams/Fighting.md
> +location accordingly, manages forces such as gravity, character weight, and impact due to combat
Would this mean you want us to add random object generation?

2021-06-08 18:20 UTC, nfarnan commented on teams/Fighting.md
> +location accordingly, manages forces such as gravity, character weight, and impact due to combat
Not necessarily. You can draw a single hazard (e.g., 1 boulder sprite), and have it fall from a single point on the map at some time interval. You are going to some extra bodies to be able to demonstrate your rigid body collision implementation, however.

2021-06-08 18:21 UTC, cps41 commented on teams/Fighting.md
> +location accordingly, manages forces such as gravity, character weight, and impact due to combat
And would it be sufficient for those objects to just disappear over time or would we have to also make them stay until they're pushed off the platform? The addition of destructible environment feels very out of scope despite this being a rigorous and time consuming course, as it is also in a shortened semester and new language to almost everybody in the class.

2021-06-08 18:28 UTC, nfarnan commented on teams/Fighting.md
> +location accordingly, manages forces such as gravity, character weight, and impact due to combat
This is not really a destructible environment because the world, itself can stay static. This is adding another entity into the game as a way to demonstrate the physics engine. I would be fine with them disappearing overtime or just coming in at a trajectory that would send them off the map (could even combine with making them frictionless so that they do not slow down when "rolling" across the map).

2021-06-08 18:29 UTC, nfarnan commented on teams/Fighting.md
> +location accordingly, manages forces such as gravity, character weight, and impact due to combat
Also, as to your note about the shortened term, typically, this course is run with teams of 10-12 students divided into 3 advanced topics per game. I am already accounting for the reduced length of the term in this suggestion. During a standard term I probably would have been adding the requirement of fully destructible environments.

2021-06-08 18:36 UTC, cps41 commented on teams/Fighting.md
> +location accordingly, manages forces such as gravity, character weight, and impact due to combat
Updated!

2021-06-08 18:38 UTC, nfarnan commented on teams/Fighting.md
> +location accordingly, manages forces such as gravity, character weight, and impact due to combat
No apology necessary! I'm glad everything is clarified now, and I want to note that is was admirable of you to stand up for your teammates and their workload over the term. You made some great points, it is just that I had already considered those same points in my initial suggestion.

Great work!

2021-06-08 18:39 UTC, cps41 commented on teams/Fighting.md
> +location accordingly, manages forces such as gravity, character weight, and impact due to combat
Thank you!

2021-06-08 18:39 UTC, merged