Team IDK Proposal
nfarnan/cs1666_organization pull request #4
Opened 2022-09-20 02:24 UTC by Yanding-Liu

2022-09-20 17:48 UTC, nfarnan requested changes

2022-09-20 17:48 UTC, nfarnan commented on teams/Team_IDK_description.md
> +  Once we’ve created the Delaunay triangulation graph, we will calculate the minimum spanning tree using Prim’s algorithm or Dijkstra’s algorithm to find the main routing path between the rooms. We w
Dijkstra's is a shortest paths algorithm, not MST.

2022-09-20 17:48 UTC, nfarnan commented on teams/Team_IDK_description.md
> +
To be clear, you're going to have to run the learning through a large number of simulated battles to train a policy that will actually be used in-game, correct?

2022-09-20 17:48 UTC, nfarnan commented on teams/Team_IDK_description.md
> +* Have a working map/room
I'm fine with a placeholder non-generated map for the midterm

2022-09-20 17:48 UTC, nfarnan commented on teams/Team_IDK_description.md
> +* Implement combat moveset/system
How many moves to support? I'm fine with a naive dummy AI for the midterm

2022-09-20 17:48 UTC, nfarnan commented on teams/Team_IDK_description.md
> +  * Player can choose moves (10%)
How many moves, how complex will the combat be?

2022-09-20 17:48 UTC, nfarnan commented on teams/Team_IDK_description.md
> +  * Display UI (5%)
Specifically what UI elements do you want to display?

2022-09-20 17:48 UTC, nfarnan commented on teams/Team_IDK_description.md
> +  * Have AI work with basic moveset (10%)
Need more details on differences between basic and advanced movesets

2022-09-20 17:48 UTC, nfarnan commented on teams/Team_IDK_description.md
> +  * Character can interact with map/room (10%)
What iteractions specifically do you want to support?

2022-09-20 17:48 UTC, nfarnan commented on teams/Team_IDK_description.md
> +  * Randomly generated map made of rooms (10%)
How big of a map do you plan to generate?

2022-09-20 17:48 UTC, nfarnan commented on teams/Team_IDK_description.md
> +  * Randomly generated room (10%)
How big will the rooms be? How many rooms per map?

2022-09-21 02:25 UTC, mws69 commented on teams/Team_IDK_description.md
> +  * Randomly generated map made of rooms (10%)
1000x1000 “tiles” within the 2-D array (grid)

2022-09-21 02:25 UTC, mws69 commented on teams/Team_IDK_description.md
> +  * Character can interact with map/room (10%)
Character can interact with level exit, pick up keys, move around, collide with walls/objects

2022-09-21 02:28 UTC, mws69 commented on teams/Team_IDK_description.md
> +  * Randomly generated room (10%)
12 rooms per map, (ranging from 6x6 to 12x12 “tiles” within the 2-D array)

2022-09-21 02:29 UTC, mws69 commented on teams/Team_IDK_description.md
> +  Once we’ve created the Delaunay triangulation graph, we will calculate the minimum spanning tree using Prim’s algorithm or Dijkstra’s algorithm to find the main routing path between the rooms. We w
*Prim's or Kruskal's

2022-09-21 13:19 UTC, nfarnan commented
Please update the proposal and PR with the changes and updates mentioned in the discussion above.

2022-09-26 12:56 UTC, nfarnan commented on teams/Team_IDK_description.md
> +  * Player can choose moves (10%)
Given the updated description above, I'll require at least 8 moves

2022-09-26 12:59 UTC, nfarnan approved these changes

2022-09-26 12:59 UTC, merged