Update MonsterTown_manage.md
nfarnan/cs1666_organization pull request #44
Opened 2021-07-07 18:12 UTC by bhattiburhan3

2021-07-07 18:17 UTC, nfarnan requested changes
The goals seem to only deal with trainers. Have you got the map laid out as specified in your initial goals and completed the required artwork?

2021-07-07 18:17 UTC, nfarnan commented on management/MonsterTown_manage.md
> +		 1. Place NPC trainers scattered throughout the map
Normalize indentation (extra space in front of first itme).

2021-07-07 20:25 UTC, bhattiburhan3 commented on management/MonsterTown_manage.md
> +		 1. Place NPC trainers scattered throughout the map
Yeah we have all the required artwork done and the map is also completely done. The only thing from our midterm goals we have left is NPC related items

2021-07-07 20:55 UTC, bhattiburhan3 commented
I fixed the indentation as well

2021-07-08 15:43 UTC, nfarnan approved these changes

2021-07-08 15:46 UTC, merged