Added presentation outline for Puzzle Stealth Networking Team
nfarnan/cs1666_organization pull request #45
Opened 2020-10-16 04:30 UTC by patrickrhee

2020-10-19 19:51 UTC, nfarnan requested changes

2020-10-19 19:51 UTC, nfarnan commented on adv_topics/networking.md
> +		* What is each layer responsible for?
Don't need to review this

2020-10-19 19:51 UTC, nfarnan commented on adv_topics/networking.md
> +* UDP and TCP
This is fine as the purposes of TCP/UDP were under covered in the first presentation.

2020-10-19 19:51 UTC, nfarnan commented on adv_topics/networking.md
> +		* Server implementation
Be careful with a code overview, this can be tricky to do effectively in slides.

2020-10-19 21:41 UTC, patrickrhee commented on adv_topics/networking.md
> +		* Server implementation
Got it. I was thinking of having a simplified list of steps our program executes to make networking happen, but would it still be too specific/advanced for the audience?
(e.g: "Step 1 - We use our IP/Port# to create a listening socket")

2020-10-21 18:21 UTC, nfarnan approved these changes

2020-10-21 18:21 UTC, nfarnan commented on adv_topics/networking.md
> +		* Server implementation
No, I think that should be fine

2020-10-21 18:21 UTC, merged