proc level generation presentation outline
nfarnan/cs1666_organization pull request #46
Opened 2020-10-19 03:27 UTC by cjk94

2020-10-19 19:54 UTC, nfarnan requested changes
Other than cutting the intro/review of proc level gen, it looks good. Cut that and I'll approve.

2020-10-19 19:54 UTC, nfarnan commented on adv_topics/proc_level_gen_outline.md
> +* The problem
Cut this, already covered in previous presentations

2020-10-19 21:44 UTC, cjk94 commented on adv_topics/proc_level_gen_outline.md
> +* The problem
Done. Thank you.

2020-10-21 18:22 UTC, nfarnan approved these changes

2020-10-21 18:22 UTC, merged