AI preso 2 outline for team Roguelike
nfarnan/cs1666_organization pull request #52
Opened 2021-07-15 17:22 UTC by keyonzi

Here is our outline, sorry it was a bit late.

2021-07-15 17:56 UTC, nfarnan requested changes
Need more details on timing, also need to cut down the intro given overlap with material from the first AI presentation.

2021-07-15 17:56 UTC, nfarnan commented on adv_topics/ai.md
> +	* General introduction of what it is
Already covered in previous presentation, you should build on top of what they presented, not cover the same ground.

2021-07-15 17:56 UTC, nfarnan commented on adv_topics/ai.md
> +		* Mario AI, AI in its simplest form
Again, history was already covered. I'll allow this if it differs from previous presentation AND has some impact on your approach to your game. Be sure to contrast this with the history covered in the first presentation, though.

2021-07-15 17:56 UTC, nfarnan commented on adv_topics/ai.md
> +* Topic 1 - Deep Dive of State Machine vs Machine Learning (Neural Networks)
You annotated 10 min for intro (too much, should definitely be cut down for presentation 2). How much time for these other topics?

2021-07-16 11:39 UTC, keyonzi commented on adv_topics/ai.md
> +		* Mario AI, AI in its simplest form
We cut out the history, and kept only a general intro as a reminder. Instead our 'intro' will focus on difference between psuedointelligence and AI, and what that actually means for games. Plus we will introduce different mechanics that the other group did not.

2021-07-16 11:40 UTC, keyonzi commented on adv_topics/ai.md
> +* Topic 1 - Deep Dive of State Machine vs Machine Learning (Neural Networks)
Cut intro to 5. But included 5 for the breakdown of new types of AI. The introduction of the other AI methods (stateless, deep learning) will actually take some time. But in my fork we made that more clear.

2021-07-16 11:41 UTC, keyonzi commented
I see 'changes' requested. I commented on all of your questions. But I also updated the whole file on my fork to reflect what I said in my comments. But the option for a PR isn't there, because this one is outstanding I think. But you can look there for more details on the changes.

https://github.com/keyonzi/cs1666_organization/blob/main/adv_topics/ai.md

2021-07-16 13:51 UTC, nfarnan approved these changes

2021-07-16 13:51 UTC, merged