Completed first pass of milestones, description, and manager weeks
nfarnan/cs1666_organization pull request #6
Opened 2020-09-04 21:12 UTC by RobertXu09

Added game description
Added general milestones
Added advanced topic milestones
Added all team members to manager weeks

Only waiting for feedback, otherwise I think everything is completed

2020-09-04 22:21 UTC, nfarnan requested changes

2020-09-04 22:21 UTC, nfarnan commented on teams/SpeedRun.md
> +	* Players will be able to move their player character responsively through arrow keys
This is not a physics milestone, this is a general milestone.

2020-09-04 22:21 UTC, nfarnan commented on teams/SpeedRun.md
> +	* Players will not be able to move through each other or obstacles through a rigidbody system
This is a general milestone.

2020-09-04 22:21 UTC, nfarnan commented on teams/SpeedRun.md
> +	* Add different biomes/obstacles to terrain
What will the levels look like? What is the target size? Need more details here.

Managing procedural generation that is speed-run compatible will be tricky.

2020-09-04 22:21 UTC, nfarnan commented on teams/SpeedRun.md
> +* Create responsive platformer movement (arrow keys?) that is affected by physical interactions with the course and other players
Use of arrow keys is fine. Must also support WASD movement.

2020-09-04 22:21 UTC, nfarnan commented on teams/SpeedRun.md
>  ...
Need some more details/requirements here, e.g.:

- Will there be obstacles aside from the level geography? If so, how many different types and general properties.
- How about supporting "ghost" replays of past runs from current player and other players to benchmark yourself against? This would also require the ability to save generated levels to re-run them.
- Will all players have the same behavior or will you be able to tune attributes of the player (e.g, trade off jump height for speed, etc.) I can see arguments to be made either way. Having uniform behavior is more in line with the speed-run approach of exactly perfectly meeting the requirements of the level, but since the levels are randomly generated, being able to fine-tune the properties of the player might be a nice feature.

2020-09-05 01:08 UTC, RobertXu09 commented on teams/SpeedRun.md
>  ...
Hi Dr. Farnan, does pushing new commits automatically update the pull request?
I'll create a new pull request if it doesn't.

Anyways, I updated the file to hopefully address all of the changes you requested:

Updated general milestones to include requirements about obstacles that are definitely planned for the game to have: bouncing/rolling rocks/balls, springtraps, moving platforms, and slippery platforms with less friction.

Updated Physics Team's milestones to have more depth: the team will now simulate forces applied on players by terrain, moving obstacles, and other players; terrain; terrain will all have varying levels of friction, so that will also be needed to be accounted for; and moving obstacles (bouncing rocks/balls) will have projectile motion applied to how they move, along with interactions with other obstacles, terrain, and players.

Updated Procedural Level Generation Team's milestones to be more in depth about the desired level design. Specified size via amount of rooms/floors and time to complete. Emphasized goal on how each course will be unique (room/floor layout + obstacle placement). 

I want to address the suggestions on ghost replays/benchmarks: as a group we meant for a game where the title Multiplayer Platformer Race might be more descriptive. It is a speedy running game, but not speedrun in the sense of the timed speedruns of Games Done Quick convention. So we never planned for a ghost replay mechanic: the game we wanted wasn't one with high scores---it's one that has high replayability as a competition between friends.

Hopefully the updated requirements are in-depth and specific enough!

2020-09-05 13:43 UTC, nfarnan requested changes

2020-09-05 13:43 UTC, nfarnan commented on teams/SpeedRun.md
>  ...
Yes, the pull request was updated. All of these are great updates with more specificity! Overall I'm happy. I think you'll need a little bit more overall. How about just adding the ability to save and exchange randomly generated levels to the proc. level gen. and networking teams? This still goes with the high replay ability between friends theme, but also allows you to incorporate some of the typical speed run ideas as you'll be able to repeatedly play the same level.

2020-09-05 22:07 UTC, RobertXu09 commented on teams/SpeedRun.md
>  ...
Hi Dr. Farnan,

Added requirement to Networking and Procedural Level Generation teams' milestones for them to work with each other to create a system to save, exchange, and regenerate previously generated levels.

2020-09-07 14:39 UTC, nfarnan approved these changes

2020-09-07 14:39 UTC, merged