Update goals for week of 11/4
nfarnan/cs1666_organization pull request #62
Opened 2020-11-04 20:19 UTC by apres123

2020-11-04 21:32 UTC, nfarnan requested changes

2020-11-04 21:32 UTC, nfarnan commented on management/DungeonCrawler.md
>  		...
Need collision with walls

2020-11-04 21:37 UTC, apres123 commented on management/DungeonCrawler.md
>  		...
Added to goal 1

2020-11-05 16:47 UTC, nfarnan approved these changes

2020-11-05 16:47 UTC, merged