Proposing 11/3 - 11/9 Management Week Goals
nfarnan/cs1666_organization pull request #62
Opened 2021-11-03 18:49 UTC by arb204

Added goals for my management week.

2021-11-04 17:27 UTC, nfarnan requested changes

2021-11-04 17:27 UTC, nfarnan commented on management/Platformer.md
> +		 	- Create a bugs markdown file, to monitor bugs found with the game. Start fixing bugs as they are found.
If you'd prefer a markdown fine, but I would suggest that you use the "Issues" tracker included in GitHub, as it is designed for this purpose.

2021-11-04 17:27 UTC, nfarnan commented on management/Platformer.md
> +			- Start working on conserving forces such as momentum through portals.
Need a more specific goal. What do you want to have implemented this week to demonstrate progress here?

2021-11-05 16:05 UTC, arb204 commented on management/Platformer.md
> +			- Start working on conserving forces such as momentum through portals.
Ok I'll work on fixing this now.

2021-11-05 16:11 UTC, arb204 commented
I updated the goals for this week to be more specific. Hopefully, their more up to expectations now.

2021-11-08 15:11 UTC, nfarnan approved these changes

2021-11-08 15:11 UTC, merged