Infinite Runner Management Week 7 Goals Added
nfarnan/cs1666_organization pull request #68
Opened 2021-11-09 06:25 UTC by Bungarooo

2021-11-11 18:16 UTC, nfarnan requested changes

2021-11-11 18:16 UTC, nfarnan commented on management/InfRun.md
> +			a. Begin work on power ups
Need a more specific goal of what to accomplish this week, other than that looks good.

2021-11-11 20:39 UTC, Bungarooo commented on management/InfRun.md
> +			a. Begin work on power ups
I made a couple more commits, adding a little more description to the listed goals. I hope this is satisfactory now.

2021-11-12 16:17 UTC, nfarnan approved these changes

2021-11-12 16:17 UTC, merged