Update Platformer.md
nfarnan/cs1666_organization pull request #71
Opened 2021-11-10 14:30 UTC by Evmo98

2021-11-11 18:18 UTC, nfarnan approved these changes

2021-11-11 18:18 UTC, nfarnan commented on management/Platformer.md
> +			- Add Multithreading Support
Need  more details here. What, specifically do you want to get running in a separate thread this week?

2021-11-12 16:19 UTC, nfarnan requested changes
Need specific goals for this week on multithreading support

2021-11-12 16:35 UTC, Evmo98 commented on management/Platformer.md
> +			- Add Multithreading Support
We will have Separate Threads for Game and Network. We might even have separate threads for Listening and Sending for multiplayer.

2021-11-12 16:50 UTC, nfarnan approved these changes

2021-11-12 16:50 UTC, merged