Update Team 1 Physics Outline
nfarnan/cs1666_organization pull request #72
Opened 2022-10-19 03:26 UTC by blm135

2022-10-19 14:26 UTC, nfarnan requested changes
To help clarify, please add time estimates to teach topic. I.e., how long you plan to spend on each topic.

2022-10-19 14:26 UTC, nfarnan commented on adv_topics/Physics.md
> +	* Collision Detection
Collision detection already covered in lecture, you could go into simulating the effects of a collision (e.g., items bouncing off one another).

2022-10-27 01:09 UTC, blm135 commented
We added time estimates in and updated the section regarding rigid body collisions.

2022-10-27 16:24 UTC, nfarnan approved these changes

2022-10-27 16:24 UTC, merged