Week 8 Goals - No Manager
nfarnan/cs1666_organization pull request #74
Opened 2021-11-16 02:16 UTC by DaneHalle

No direct manager is marked for Week 8 but due to game being due in 3 weeks time, we decided to make goals for ourselves to keep ourselves in check. Figured we would make a PR with said goals so you are updated on where we are at in the game process.

2021-11-16 18:33 UTC, nfarnan commented
Noted. I won't do a demo of your game or expect a management week report, but will give feedback on the goals.

2021-11-16 18:34 UTC, nfarnan requested changes

2021-11-16 18:34 UTC, nfarnan commented on management/InfRun.md
> +			a. New terrain types and visualizations of them
What types do you hope to get done this week specifically?

2021-11-16 18:34 UTC, nfarnan commented on management/InfRun.md
> +		4. Variable jump with physics - Short press, short jump, long press, higher jump to cap out at some height
Isn't this already implemented?

2021-11-16 18:46 UTC, DaneHalle commented on management/InfRun.md
> +			a. New terrain types and visualizations of them
Here are our current ideas for new terrain work. 
1. asphalt (low friction)
2. sand (high friction)
3. water (buoyancy)

2021-11-16 18:49 UTC, DaneHalle commented on management/InfRun.md
> +		4. Variable jump with physics - Short press, short jump, long press, higher jump to cap out at some height
If referring to the camera:
Currently camera movement is set to a static speed in the x and dynamic in the y per this past week's work. 

If referring to the Bezier curve:
This past week we had work so the curves will be continuous (see attached). Currently, it is only active in our test scene instead of being utilized within the actual game,

![32151ae2813522bb6d55b7b88e6e6bcb-png](https://user-images.githubusercontent.com/29028364/142046938-b21b1903-c245-447c-9ecf-ba5955235cfc.jpg)

2021-11-17 16:08 UTC, nfarnan commented on management/InfRun.md
> +		4. Variable jump with physics - Short press, short jump, long press, higher jump to cap out at some height
Got it

2021-11-17 16:08 UTC, merged