update weekly management goal
nfarnan/cs1666_organization pull request #90
Opened 2022-11-03 00:02 UTC by Krisocer

2022-11-03 18:22 UTC, nfarnan requested changes

2022-11-03 18:22 UTC, nfarnan commented on management/Jersey_Shores.md
> +		2. Work on stemmer and add stopwords item
Specifically what word do you hope to get done this week on the stemmer and stopwords?

2022-11-03 18:22 UTC, nfarnan commented on management/Jersey_Shores.md
> +		3. Work on UI and python model
Specifically what UI work?
What Python model are you referring to?

2022-11-04 21:51 UTC, Krisocer commented on management/Jersey_Shores.md
> +		2. Work on stemmer and add stopwords item
Using crates(you have allowed our NLP group to use) to implement stemmer and stopwords.

2022-11-04 21:53 UTC, Krisocer commented on management/Jersey_Shores.md
> +		3. Work on UI and python model
For the python model: We are not actually implementing the python model in our game, and we just use it to do some tests to finish algorithm research.

For the UI: I am working on getting rover to appear and disappear on the screen, as well as getting his dialogue and the user input to show up on the screen

2022-11-14 15:45 UTC, nfarnan approved these changes

2022-11-14 15:45 UTC, merged